### ISSUE TITLE
Missing textures on the reenforced diamond armor in mod tested in creative mode toggle

### ISSUE THREAD

**Issue by Hellcommander** [ToroCraft/ToroQuest#121]
all the reenforced diamond armor in the mods have purple textures on the sleeve when worn by the player
here is the error that causes it that i tracked done in the log
`[20:12:25] [Client thread/WARN]: "net.minecraft.item.ItemStack" null inject errors: 1 in 106595 ms
[20:12:32] [Client thread/WARN]: "net.minecraft.item.ItemStack" null inject errors: 17 in 7206 ms
[20:12:40] [Client thread/WARN]: Failed to load texture: toroquest:textures/models/armor/reinforced_diamond_armor_layer_1.png
java.io.FileNotFoundException: toroquest:textures/models/armor/reinforced_diamond_armor_layer_1.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[bzr.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cae.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:34) ~[byv.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:79) [bza.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) [bza.class:?]
	at net.minecraft.client.renderer.entity.Render.func_110776_a(Render.java:146) [bus.class:?]
	at net.minecraft.client.renderer.entity.layers.LayerArmorBase.func_188361_a(LayerArmorBase.java:77) [bwz.class:?]
	at net.minecraft.client.renderer.entity.layers.LayerArmorBase.func_177141_a(LayerArmorBase.java:42) [bwz.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:508) [bvl.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:231) [bvl.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:70) [byc.class:?]
	at realrender.REN$RenderPlayerDummy.func_76986_a(REN.java:185) [REN$RenderPlayerDummy.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.redirect$onRenderEntity$zzh000(RenderManager.java:677) [bur.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:415) [bur.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392) [bur.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:810) [bqm.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1757) [bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1582) [bqe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1359) [bqe.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by frodare** [comment]
That armor is not currently supported was suppose to be removed. I will keep this issue open to track the progress of its removal or implementation.
