### ISSUE TITLE
Error when accepting a quest

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#159]
[21:18:32] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException: village lord not found
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:795) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:740) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:589) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException: village lord not found
	at net.torocraft.toroquest.gui.VillageLordGuiHandler.getVillageLord(VillageLordGuiHandler.java:63) ~[VillageLordGuiHandler.class:?]
	at net.torocraft.toroquest.network.message.MessageQuestUpdate$Worker.work(MessageQuestUpdate.java:64) ~[MessageQuestUpdate$Worker.class:?]
	at net.torocraft.toroquest.network.message.MessageQuestUpdate$Handler$1.run(MessageQuestUpdate.java:212) ~[MessageQuestUpdate$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 5 more

**Comment by zeriley** [comment]
I am working on switching this to a packet system like @frodare did in the Nemesis system:
https://github.com/ToroCraft/NemesisSystem/blob/1f2b67f6173386eb314298c2df0c4bf32319e189/java/net/torocraft/nemesissystem/NemesisSystemCommand.java#L112

https://github.com/ToroCraft/NemesisSystem/blob/master/java/net/torocraft/nemesissystem/network/MessageOpenNemesisGui.java
