### ISSUE TITLE
Doesn't work with Tough as Nails

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#17]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 11/16/16 9:47 PM
Description: Unexpected error

java.lang.ClassCastException: net.torocraft.toroquest.civilization.player.PlayerCivilizationCapabilityImpl cannot be cast to toughasnails.temperature.TemperatureHandler
	at toughasnails.handler.temperature.TemperatureOverlayHandler.onPostRenderOverlay(TemperatureOverlayHandler.java:64)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_97_TemperatureOverlayHandler_onPostRenderOverlay_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:888)
	at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:133)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1369)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at toughasnails.handler.temperature.TemperatureOverlayHandler.onPostRenderOverlay(TemperatureOverlayHandler.java:64)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_97_TemperatureOverlayHandler_onPostRenderOverlay_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:888)
	at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:133)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['frodare'/2041, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (160,64,280), Chunk: (at 0,4,8 in 10,17; contains blocks 160,0,272 to 175,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['frodare'/2041, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.19.0-30-generic
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 484026312 bytes (461 MB) / 888487936 bytes (847 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.1.2075 Optifine OptiFine_1.10.2_HD_U_C3 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2075.jar) 
	UCHIJA	Forge{12.18.1.2075} [Minecraft Forge] (forge-1.10.2-12.18.1.2075.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2080} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2080-universal.jar) 
	UCHIJA	dailies{1.10.2-6} [Bailey's Dailies] (dailies-1.10.2-6.jar) 
	UCHIJA	dldungeonsjdg{1.8.13} [Doomlike Dungeons] (dld-pre1.jar) 
	UCHIJA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJA	teletoro{1.10.2-19} [TeleToro] (teletoro-1.10.2-19.jar) 
	UCHIJA	torcharrowsmod{1.10.2-1} [TorchArrowsMod] (torcharrows-1.10.2-1.jar) 
	UCHIJA	torohealthmod{1.10.2-1} [ToroHealth Damage Indicators] (torohealth-1.10.2-1.jar) 
	UCHIJA	toroquest{1.10.2-1} [ToroQuest] (toroquest-1.10.2-1.jar) 
	UCHIJA	torobasemod{1.0} [ToroBaseMod] (toroquest-1.10.2-1.jar) 
	UCHIJA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	Loaded coremods (and transformers): 
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 346.96' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: 1.10
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 346.96, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: rhapsodia-0.6.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 346.96
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by frodare** [comment]
#Server Side

[02:47:32] [Server thread/WARN]: Failed to handle packet for /68.63.44.191:46477
java.lang.ClassCastException: net.torocraft.toroquest.civilization.player.PlayerCivilizationCapabilityImpl cannot be cast to toughasnails.api.stat.StatHandlerBase
	at toughasnails.handler.ExtendedStatHandler.onPlayerLogin(ExtendedStatHandler.java:48) ~[ExtendedStatHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_ExtendedStatHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:565) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:228) ~[mp.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

**Comment by zeriley** [comment]
Martine fixed this, correct?

**Comment by Wing01** [comment]
Yes, seems to be fixed
