### ISSUE TITLE
Another crash report!

### ISSUE THREAD

**Issue by Hypsandar** [ToroCraft/ToroQuest#173]
The error said that toroquest made the game fail, here's the crash report.
Possibly incompatibility with other mods. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.12-3.0.0.60-universal.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 7/15/17 1:57 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ToroQuest (toroquest)
Caused by: java.lang.NullPointerException
	at net.minecraftforge.client.ItemModelMesherForge.func_178086_a(ItemModelMesherForge.java:57)
	at net.torocraft.toroquest.block.BlockToroSpawner.registerRenders(BlockToroSpawner.java:50)
	at net.torocraft.toroquest.block.ToroQuestBlocks.registerRenders(ToroQuestBlocks.java:6)
	at net.torocraft.toroquest.ClientProxy.init(ClientProxy.java:25)
	at net.torocraft.toroquest.ToroQuest.init(ToroQuest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:625)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:781)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 193825888 bytes (184 MB) / 636862464 bytes (607 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2413 Optifine OptiFine_1.12_HD_U_C4 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2413.jar) 
	UCHI	forge{14.21.1.2413} [Minecraft Forge] (forge-1.12-14.21.1.2413.jar) 
	UCHI	ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.1-9.jar) 
	UCHI	biomesoplenty{7.0.0.2289} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2289-universal.jar) 
	UCHI	calculations{1.1.0} [Calculations] (Calculations-1.12-1.1.0.jar) 
	UCHI	customcrosshairmod{0.8.1} [Custom Crosshair Mod] (crosshairmod-v0.8.1-forge-mc1.12.jar) 
	UCHI	lostcities{0.0.17beta} [The Lost Cities] (lostcities-1.12-0.0.17beta.jar) 
	UCHI	neat{1.4-15} [Neat] (Neat 1.4-15.jar) 
	UCHI	notenoughwands{1.5.7} [Not Enough Wands] (notenoughwands-1.12-1.5.7.jar) 
	UCHI	notes{1.1.1} [Notes] (Notes-1.12-1.1.1.jar) 
	UCHI	thutcore{5.4.0} [Thut Core] (thutcore-5.4.0.jar) 
	UCHE	toroquest{1.11.2-5.0} [ToroQuest] (toroquest-1.12-5.0.jar) 
	UCHI	toughasnails{3.0.0.60} [Tough As Nails] (ToughAsNails-1.12-3.0.0.60-universal.jar) 
	UCHI	waystones{4.0.5} [Waystones] (Waystones_1.12-4.0.5..jar) 
	UCHI	xaerominimap{1.13.1} [Xaero's Minimap] (Xaeros_Minimap_1.13.1_Forge_1.12.jar) 
	UCHI	xaeroworldmap{1.9} [Xaero's World Map] (XaerosWorldMap_b1.9_Forge_1.12.jar) 
	Loaded coremods (and transformers): 
TANLoadingPlugin (ToughAsNails-1.12-3.0.0.60-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4531
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by frodare** [comment]
Forge 1.12 is sure keeping us on our toes, thanks for reporting the issue.

**Comment by Hypsandar** [comment]
No problem, i want it fixed as much as you do!

**Comment by zeriley** [comment]
I could not reproduce this issue, but I fixed what appeared to be the problem.  Please try the latest update (1.12-5.2) and let us know if you continue to experience this issue.
