### ISSUE TITLE
Server Exception:  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#76]
[17:22:10] [Server thread/INFO]: frodare joined the game
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: java.util.ConcurrentModificationException
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at net.minecraft.util.ClassInheritanceMultiMap.<init>(SourceFile:26)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:88)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:433)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:139)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:104)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:68)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:22:11] [Chunk I/O Executor Thread-1/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by frodare** [comment]
Probably caused by: https://github.com/MinecraftForge/MinecraftForge/pull/3485
