### ISSUE TITLE
Crashy

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroQuest#83]
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:254) [SimpleNetworkWrapper.class:?]
        at net.torocraft.toroquest.civilization.player.PlayerCivilizationCapabilityImpl.syncClient(PlayerCivilizationCapabilityImpl.java:72) [PlayerCivilizationCapabilityImpl.class:?]
        at net.torocraft.toroquest.network.message.MessageRequestPlayerCivilizationSync$Handler$1.run(MessageRequestPlayerCivilizationSync.java:50) [MessageRequestPlayerCivilizationSync$Handler$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
        at net.torocraft.toroquest.civilization.Province.writeNBT(Province.java:77) ~[Province.class:?]
        at net.torocraft.toroquest.network.message.MessagePlayerCivilizationSetInCiv.toBytes(MessagePlayerCivilizationSetInCiv.java:38) ~[MessagePlayerCivilizationSetInCiv.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:?]
        ... 18 more
[18:05:01] [Server thread/INFO]: Defehate lost connection: TextComponent{text='A fatal error has occurred, this connection is terminated', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[18:05:01] [Server thread/INFO]: Defehate left the game
[18:05:01] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerEvent$SaveToFile@14413715:
java.lang.NullPointerException
        at net.torocraft.toroquest.civilization.Province.writeNBT(Province.java:77) ~[Province.class:?]
        at net.torocraft.toroquest.civilization.player.PlayerCivilization.writeNBT(PlayerCivilization.java:41) ~[PlayerCivilization.class:?]
        at net.torocraft.toroquest.civilization.CivilizationHandlers.onSave(CivilizationHandlers.java:103) ~[CivilizationHandlers.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_CivilizationHandlers_onSave_SaveToFile.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
        at net.minecraftforge.event.ForgeEventFactory.firePlayerSavingEvent(ForgeEventFactory.java:324) [ForgeEventFactory.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75753_a(SaveHandler.java:195) [bbt.class:?]
        at net.minecraft.server.management.PlayerList.func_72391_b(PlayerList.java:333) [mt.class:?]
        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:369) [mt.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:795) [mi.class:?]
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:451) [er.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) [mh.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

**Comment by frodare** [comment]
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:254) ~[SimpleNetworkWrapper.class:?]
        at net.torocraft.toroquest.civilization.player.PlayerCivilizationCapabilityImpl.syncClient(PlayerCivilizationCapabilityImpl.java:72) ~[PlayerCivilizationCapabilityImpl.class:?]
        at net.torocraft.toroquest.network.message.MessageRequestPlayerCivilizationSync$Handler$1.run(MessageRequestPlayerCivilizationSync.java:50) ~[MessageRequestPlayerCivilizationSync$Handler$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_71]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) ~[lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
        at net.torocraft.toroquest.civilization.Province.writeNBT(Province.java:77) ~[Province.class:?]
        at net.torocraft.toroquest.network.message.MessagePlayerCivilizationSetInCiv.toBytes(MessagePlayerCivilizationSetInCiv.java:38) ~[MessagePlayerCivilizationSetInCiv.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:?]
        ... 18 more
[18:07:57] [Netty Epoll Server IO #1/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
[18:07:57] [Server thread/INFO]: frodare lost connection: TextComponent{text='A fatal error has occurred, this connection is terminated', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
